config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'products#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :product_images, only:[:new, :create, :index, :show, :destroy]
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    post '/favorites_create_for_index/', to: 'favorites#create_for_index'
    delete '/favorites_delete_for_index/', to: 'favorites#destroy_for_index'
    
    
  end

 # resources :product_images, only: [:new, :create, :index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

    belongs_to :user
    belongs_to :product
    
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :product_images, dependent: :destroy
  accepts_nested_attributes_for :product_images  # added

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/product_image.rb
class ProductImage < ApplicationRecord

    belongs_to :product
    attachment :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :product_images, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

    def create
        product = Product.find(params[:product_id])
        favorite = current_user.favorites.new(product_id: product.id)
        favorite.save
        redirect_to product_path(product)
    end

    def create_for_index
        product = Product.find(params[:product_id])
        favorite = current_user.favorites.new(product_id: product.id)
        favorite.save
        redirect_to products_path
    end
  
  
    def destroy
        product = Product.find(params[:product_id])
        favorite = current_user.favorites.find_by(product_id: product.id)
        favorite.destroy
        redirect_to product_path(product)
    end

    def destroy_for_index
        product = Product.find(params[:product_id])
        favorite = current_user.favorites.find_by(product_id: product.id)
        favorite.destroy
        redirect_to products_path
    end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
    def create
        product = Product.find(params[:product_id])
        comment = current_user.post_comments.new(post_comment_params)
        comment.product_id = product.id
        comment.save
        redirect_to product_path(product)
    end
  
    def destroy
        PostComment.find_by(id: params[:id], product_id: params[:product_id]).destroy
    redirect_to product_path(params[:product_id])

    end

    private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/product_images_controller.rb
class ProductImagesController < ApplicationController

    def new
        @product_image = ProductImage.new
    end
  
    def create
        @product_image = ProductImage.new(product_image_params)
    @product_image.user_id = current_user.id
    @product_image.save
    redirect_to product_images_path
    end
  
    def index
        @product_images = ProductImage.all
    end
  
    def show
    end
  
    def destroy
    end

    private

  def product_image_params
    params.require(:product_image).permit(:title, :product_name, :body, :image)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    
    @products = Product.all
    @product = Product.new

    @product.product_images.build # added
    @product.product_images.build # added
  
    
  end

  def show
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless user_signed_in?
    if user_signed_in? 
      @product = Product.find(params[:id])
      @post_comment = PostComment.new
    end
    
  end

  def new
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless user_signed_in?
    if user_signed_in? 
    @product = Product.new
    end
  end

  def create
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless user_signed_in?
    if user_signed_in?
    user_id = current_user.id
    
    product = Product.new(product_params.merge({user_id: user_id}))
    product.save!
    redirect_to products_path(product.id)
    end
  end


  def edit
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless user_signed_in?
    if user_signed_in? 
    @product = Product.find(params[:id])
    end
  end

  def update
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless user_signed_in?
    if user_signed_in? 
    product = Product.find(params[:id])
    product.update(product_params)
    redirect_to product_path(product)
    end
  end

  def destroy
    flash[:notice] = "ログイン済ユーザーのみ記事の詳細を確認できます" unless user_signed_in?
    if user_signed_in? 
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
    end
  end


  private
  def product_params
    t = params.require(:product).permit(:title, :product_name, :body, product_images_attributes:[:image])
    t[:product_images_attributes] = t[:product_images_attributes].to_h.values
    t
    # huga = []
    # tmp[:product_images_attributes].each do |k,v|
    #   huga.push({image: v[:image], user_id: current_user.id})
    # end
    # tmp[:product_images_attributes] = huga
    # byebug
    
  end
  
end

# tmp = {product_images_attributes:1, b:2}
# tmp[:product_images_attributes]

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/product_images_helper.rb
module ProductImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UFO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <% if user_signed_in? %>
  

    <li>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    </li>
  <% else %>
    <li>
      <%= link_to "新規登録", new_user_registration_path %>
    </li>
    <li>
      <%= link_to "ログイン", new_user_session_path %>
    </li>
  <% end %>

  　　
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: key) %>
        <% end %>
    <%= yield %>
  </body>
</html>

app/views/product_images/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <%= f.submit '投稿' %>
<% end %>

app/views/products/edit.html.erb
<% if user_signed_in? %>

  <h1>編集画面</h1>
  <!-- form_with部分 -->
  <%= form_with model:@product, local: true do |f| %>
    <h4>タイトル</h4>
    <%= f.text_field :title %>
    <h4>商品名</h4>
    <%= f.text_field :product_name%>
    <h4>本文</h4>
    <%= f.text_area :body %>
    <%= f.submit '保存' %>
  <% end %>
<% end %>

app/views/products/index.html.erb
<div class="font">
<h1>UFO紹介ページ</h1>
</div>

<body>
<p id="notice"></p>

<table class="table table-striped">
    <thead>
    <tr>
    <th>ユーザー</th>
    <th>タイトル</th>
    <th>商品名</th>
    <th>本文</th>

    <th colspan="3"></th>
    </tr>
    
    </thead>

    <tbody>
        <% @products.each do |product| %>
            <tr>
            　　<td><%= product.user.name %></td>
                <td><%= product.title %></td>
                <td><%= product.product_name %></td>
                <td><%= product.body %></td>
                <td>
                    <% product.product_images.each do |image| %>
                        <%= attachment_image_tag image, :image, :fill, 100, 100, format: 'jpeg'  %>
                    <% end %>
                </td>
                
                    <td><%= link_to "#{product.post_comments.count} コメント", product_path(product.id) %></td>
                
                <td><%= link_to "詳細ページ", product_path(product) %></td>
                <td><%= link_to "編集", edit_product_path(product) %></td>
                <% if user_signed_in? %>
                <td><%= link_to "削除", product_path(product), method: :delete, data: {confirm: "ほんとに消す？"} %></td>
                <% end %>


                <td><% if product.favorited_by?(current_user) %>
                    <p>
                    <%= link_to product_favorites_delete_for_index_path(product.id), method: :delete do %>
                        ♥<%= product.favorites.count %> いいね
                    <% end %>
                    </p>
                <% else %>
                    <p>
                    <%= link_to product_favorites_create_for_index_path(product.id), method: :post do %>
                        ♡<%= product.favorites.count %> いいね
                    <% end %>
                    </p>
                <% end %>
                </td>

                


            </tr>
                    
        <% end %>
  
   
    </tbody>
 
</table>

<% if user_signed_in? %>
    <h4>新規投稿</h4>
    あなたがオススメしたいUFOを投稿しよう！
    <%= form_for(@product) do |f| %>
        <h7>タイトル</h7>
        <%= f.text_field :title %>
        <h7>商品名</h7>
        <%= f.text_field :product_name %>
        <h7>本文</h7>
        <%= f.text_area :body %>
        <h7>画像アップロード</h7>
        <%= f.fields_for :product_images do |image| %>
          <%= image.attachment_field :image %>
        <% end %>
          
        <%= f.submit '投稿' %>
    <% end %>
<% end %>

</body>

app/views/products/new.html.erb
<h1>新規投稿</h1>
あなたがオススメしたいUFOを投稿しよう！
<%= form_for(@product) do |f| %>

  <h4>タイトル</h4>
  <%= f.text_field :title %>

  <h4>商品名</h4>
  <%= f.text_field :product_name %>

  <h4>本文</h4>
  <%= f.text_area :body %>

  <h4>画像アップロード</h4>
  <%= form_with model: @product.product_images.new, local:true do |f| %>
  <%= f.attachment_field :image %>
  <% end %>


  <%= f.submit '投稿' %>
  

<% end %>

app/views/products/show.html.erb
<% if user_signed_in? %>
<h1>商品</h1>

<%= @product.title %>
<%= @product.product_name %>
<%= @product.body %>
<%= @product.created_at.strftime('%Y/%m/%d %H:%M:%S') %>

<%= link_to "一覧へ戻る", products_path %>
<%= link_to "編集", edit_product_path(@product) %>
<%= link_to "削除", product_path(@product), method: :delete, data: {confirm: "ほんとに消す？"} %> 
<% end %>

<div class="comments">
<p>コメント件数：<%= @product.post_comments.count %></p>
<% @product.post_comments.each do |post_comment| %>
  
  <%= post_comment.user.name %>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
        <% if post_comment.user == current_user %>
            <div class="comment-delete">
                <%= link_to "削除", product_post_comment_path(post_comment.product, post_comment), method: :delete %>
                
            </div>
        <% end %>
<% end %> 
<% if @product.favorited_by?(current_user) %>
    <p>
      <%= link_to product_favorites_path(@product), method: :delete do %>
        ♥<%= @product.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to product_favorites_path(@product), method: :post do %>
        ♡<%= @product.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>
  
</div>
<div class="new-comment">
<%= form_with(model:[@product, @post_comment], local: true) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>